_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
data:
    value:
        categorical_encoding: onehot
        categorical_threshold: 10
        correlation_strength: 0.5
        missing_mechanism: MCAR
        missing_ratio: 0.2
        n_categorical: 5
        n_features: 20
        n_samples: 10000
        noise_std: 0.1
        scaling_method: standard
        use_augmentation: true
        use_synthetic: true
experiment:
    value:
        checkpoint_dir: ./checkpoints
        data_dir: ./data
        device: cuda
        experiment_name: hybrid_imputation_v1
        experiment_version: "1.0"
        log_dir: ./logs
        log_interval: 100
        num_workers: 4
        pin_memory: true
        results_dir: ./results
        save_interval: 1000
        use_wandb: true
model:
    value:
        batch_size: 64
        dropout_rate: 0.1
        early_stopping_patience: 10
        gradient_clip_val: 1
        hidden_dims:
            - 256
            - 128
            - 64
        kl_weight: 0.1
        latent_dim: 32
        learning_rate: 0.001
        min_lr: 1e-06
        model_type: hybrid
        n_epochs: 100
        n_heads: 4
        reconstruction_weight: 1
        scheduler_factor: 0.5
        scheduler_patience: 5
        test_split: 0.1
        uncertainty_weight: 0.1
        validation_split: 0.2
        weight_decay: 1e-05
