model:
  model_type: "hybrid"
  hidden_dims: [256, 128, 64]
  latent_dim: 32
  n_heads: 4
  dropout_rate: 0.1
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.00001
  n_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  reconstruction_weight: 1.0
  kl_weight: 0.1
  uncertainty_weight: 0.1
  bn_weight: 0.5
  confidence_weight: 0.1
  scheduler_factor: 0.5
  scheduler_patience: 5
  min_lr: 0.000001
  validation_split: 0.2
  test_split: 0.1

experiment:
  experiment_name: "hybrid_imputation_v1"
  experiment_version: "1.0"
  data_dir: "./data"
  checkpoint_dir: "./checkpoints"
  results_dir: "./results"
  log_dir: "./logs"
  use_wandb: true
  log_interval: 100
  save_interval: 1000
  device: "cuda"
  num_workers: 4
  pin_memory: true

data:
  missing_ratio: 0.2
  categorical_threshold: 10
  scaling_method: "standard"
  use_augmentation: true
  noise_std: 0.1
  use_synthetic: true
  n_samples: 10000
  n_features: 20
  n_categorical: 5
  correlation_strength: 0.5
  seed: 42